BookConstants = {
  BOOKS_RECEIVED: "BOOKS_RECEIVED",
  BOOK_RECEIVED: "BOOK_RECEIVED",
  SHELF_UPDATED: "SHELF_UPDATED",
  BOOKSHELF_BOOKS_RECEIVED: "BOOKSHELF_BOOKS_RECEIVED"
}

module.exports = BookConstants;
